### ISSUE TITLE
Consider pre-bulding styles instead building them in runtime.

### ISSUE THREAD

**Issue by wgrabowski** [zkamil/ramlo#10]
When generating docs on Ubuntu 16.04 usign global installation of ralmo, 
`starting ramlo...`
`fs.js:634`
`return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);`
`^`
` `
` Error: EACCES: permission denied, open '/usr/lib/node_modules/ramlo/src/main.css'`
`    at Error (native)`
`    at Object.fs.openSync (fs.js:634:18)`
`    at Object.fs.writeFileSync (fs.js:1327:33)`
`    at Object.<anonymous> (/usr/lib/node_modules/ramlo/ramlo.js:50:8)`
`    at Module._compile (module.js:541:32)`
`    at Object.Module._extensions..js (module.js:550:10)`
`    at Module.load (module.js:458:32)`
`    at tryModuleLoad (module.js:417:12)`
`    at Function.Module._load (module.js:409:3)`
`    at Function.Module.runMain (module.js:575:10)`

By default installing global npm packages under Ubuntu must be done as a root or with `sudo` command.

Therefore non-root user doesn't have write access to files of package installed globally.

Is there any particular reason that styles are compiled in run time?

**Comment by kamilzasada** [comment]
Styles aren't compiled in run-time anymore. Please check v0.2.1.
