### ISSUE TITLE
ramlo script need to be  `:set ff=unix` in vim

### ISSUE THREAD

**Issue by iwanbk** [zkamil/ramlo#3]
I got this error when executing `ramlo` on Mac

```
#ramlo -f ./api.raml 
env: node\r: No such file or directory
```

It get fixed by open ramlo binary/script in vim and execute `:set ff=unix`

**Comment by kamilzasada** [comment]
Hi. Thank you for reporting an issue. In next days I'll try to reproduce a bug and publish new package with fix.

**Comment by kamilzasada** [comment]
@iwanbk I've already pushed version 0.1.1 to the NPM registry. Please tell me if you will still have this problem in the newest version.

**Comment by iwanbk** [comment]
@kamilzasada it works. Thanks!
