### ISSUE TITLE
Apidoc generation - sass / bootstrap issue on npm v3

### ISSUE THREAD

**Issue by prvdph** [zkamil/ramlo#6]
On npm@3 generation of apidoc throws an error:

Error: File to import not found or unreadable: _../../node_modules/bootstrap/scss/variables_
Parent style sheet: _./ramlo/src/styles/_bootstrap.scss_

Import statements in scss files have relative paths pointing to _ramlo/node_modules/bootstrap_ directory, which might not be present when usign npm v3 with flat directory structure of dependencies

**Comment by adanieljsinclair** [comment]
Is there a workaround for this in the meantime?

**Comment by adanieljsinclair** [comment]
I installed npm 4.4.5 as described on the main page, and I still get this issue.

**Comment by adanieljsinclair** [comment]
OK. I worked around this by going to the node_modules under ramlo and installing the specific bootstrap v4;

c:\Program Files\nodejs\node_modules\ramlo>**npm install bootstrap@4.0.0-alpha.2**

**Comment by kamilzasada** [comment]
Now _bootstrap_ and _node-sass_ are not needed in process of creating documentation. All styles would be compiled before publishing new version of ramlo. Please check v0.2.1.
